export type StudyTopic = {
  id: string;
  name: string;
  short: string;
  description: string;
  accent: string;
};

export type Question = {
  id: number;
  topic: string;
  prompt: string;
  choices: string[];
  answer: number;
  explanation: string;
  reference: string;
};

export type PracticalStation = {
  id: string;
  number: string;
  title: string;
  time: string;
  brief: string;
  checks: string[];
};

export type ProgressState = {
  bestScore: number;
  answered: number;
  stations: string[];
  readiness: number[];
};

export const topics: StudyTopic[] = [
  { id: "surface", name: "Surface preparation", short: "Prep", description: "Diagnose failure, repair substrates, remove contamination, feather edges, and create a sound profile before coating.", accent: "orange" },
  { id: "coatings", name: "Coatings & materials", short: "Coatings", description: "Select primers and finishes, read product data, understand sheen and cure, and avoid incompatible systems.", accent: "cobalt" },
  { id: "application", name: "Application methods", short: "Application", description: "Brush, roll, and airless-spray with clean cut lines, even film, controlled overlap, and equipment awareness.", accent: "acid" },
  { id: "safety", name: "Safety, PPE & hazards", short: "Safety", description: "Use labels and SDSs, control exposure, recognize lead and spray hazards, and understand respiratory requirements.", accent: "red" },
  { id: "access", name: "Ladders, scaffolds & access", short: "Access", description: "Choose, inspect, place, and use access equipment while protecting coworkers, riders, and the work zone.", accent: "purple" },
  { id: "math", name: "Math & estimating", short: "Math", description: "Calculate areas, coverage, coats, waste, scaled dimensions, and multi-component mix quantities.", accent: "teal" },
  { id: "drawings", name: "Drawings, tools & glazing", short: "Tools", description: "Read plans and work orders, select hand and power tools, maintain equipment, and handle basic glazing tasks.", accent: "yellow" },
  { id: "transit", name: "Transit job scenarios", short: "Job site", description: "Plan safe work around active public facilities, protect operations, communicate hazards, and leave a clean work area.", accent: "pink" },
];

export const questions: Question[] = [
  { id: 1, topic: "surface", prompt: "An existing wall coating is peeling in sheets. What should happen before a new finish coat is applied?", choices: ["Apply a thicker finish coat", "Remove unsound coating and determine the cause", "Wet the wall and paint immediately", "Use a longer-nap roller"], answer: 1, explanation: "A finish coat is only as sound as the surface below it. Remove loose material and correct moisture, contamination, or adhesion problems first.", reference: "Professional surface-preparation practice" },
  { id: 2, topic: "surface", prompt: "A hard, glossy painted surface is sound but will receive another coat. The best preparation is to:", choices: ["Polish it", "Scuff or degloss it, then clean it", "Add water to the new paint", "Apply finish directly over dust"], answer: 1, explanation: "A sound glossy surface needs cleaning and a profile so the next coating can develop adhesion.", reference: "Manufacturer product-data guidance" },
  { id: 3, topic: "surface", prompt: "After sanding joint compound, what must be removed before priming?", choices: ["The paper face", "All sanding dust", "Every feathered edge", "The corner bead"], answer: 1, explanation: "Residual dust interferes with primer adhesion and can create a rough, weak finish.", reference: "Professional drywall-finishing practice" },
  { id: 4, topic: "surface", prompt: "Bare steel begins showing light flash rust before priming. What is the correct response?", choices: ["Trap it under primer", "Remove the rust and restore the specified preparation", "Wipe it with water only", "Apply finish without primer"], answer: 1, explanation: "Rust and other corrosion products are unsound. Restore the required cleanliness and profile before coating.", reference: "Professional steel-preparation practice" },
  { id: 5, topic: "surface", prompt: "Before coating concrete, the painter should verify that it is sound, clean, and:", choices: ["Highly polished", "Dry enough for the specified coating", "Covered with form oil", "Still releasing curing water"], answer: 1, explanation: "Moisture and curing compounds can prevent adhesion or cause blistering. Follow the coating data sheet for moisture and cure requirements.", reference: "Manufacturer product-data guidance" },
  { id: 6, topic: "surface", prompt: "Why are the edges of remaining sound paint feather-sanded after loose paint is removed?", choices: ["To increase color strength", "To create a smooth transition that will not telegraph", "To make the wall absorb water", "To replace primer"], answer: 1, explanation: "Feathering tapers the edge between bare and coated areas so the repair does not show through the finish.", reference: "Professional surface-preparation practice" },

  { id: 7, topic: "coatings", prompt: "What is the primary job of a corrosion-resistant primer on properly prepared steel?", choices: ["Increase gloss only", "Promote adhesion and protect the substrate", "Remove mill scale", "Replace surface cleaning"], answer: 1, explanation: "Primer bonds the prepared substrate to the coating system and provides the specified protective properties.", reference: "Professional coating-system practice" },
  { id: 8, topic: "coatings", prompt: "A two-component coating must be mixed 4:1. What controls the exact components, induction time, and usable pot life?", choices: ["The wall color", "The product data sheet", "The roller frame", "The room dimensions"], answer: 1, explanation: "The manufacturer’s current technical data governs ratio, induction, thinning, pot life, recoat window, and cure.", reference: "Manufacturer technical data sheet" },
  { id: 9, topic: "coatings", prompt: "Compared with a flat finish, a gloss finish generally:", choices: ["Hides surface defects better", "Highlights more surface defects", "Requires no preparation", "Cannot be washed"], answer: 1, explanation: "Higher sheen reflects more light and usually makes waviness, patches, and tool marks more visible.", reference: "Professional finish-selection practice" },
  { id: 10, topic: "coatings", prompt: "What should be checked before placing a new coating over an unknown existing finish?", choices: ["Only the color name", "Compatibility and adhesion", "The painter’s shoe size", "Whether the room has outlets"], answer: 1, explanation: "Identify the existing system when possible, check compatibility, and perform the specified adhesion or test-patch procedure.", reference: "Manufacturer compatibility guidance" },
  { id: 11, topic: "coatings", prompt: "Which coating family is commonly selected for strong chemical and abrasion resistance on properly prepared surfaces?", choices: ["Epoxy", "Whitewash", "Wallpaper paste", "Drywall mud"], answer: 0, explanation: "Epoxy systems are commonly used where chemical and abrasion resistance are needed, subject to the product’s limitations and exposure conditions.", reference: "Professional coating-selection practice" },
  { id: 12, topic: "coatings", prompt: "Why must a painter track a coating’s recoat window?", choices: ["It determines ladder height", "Recoating too early or late can affect cure and intercoat adhesion", "It replaces wet-film checks", "It changes surface area"], answer: 1, explanation: "The data sheet defines when another coat can be applied and what preparation is needed if the maximum window is exceeded.", reference: "Manufacturer technical data sheet" },

  { id: 13, topic: "application", prompt: "The best way to reduce lap marks while rolling a large wall is to:", choices: ["Let each strip dry before the next", "Maintain a wet edge", "Roll with a dry cover", "Skip back-rolling"], answer: 1, explanation: "Work from wet into wet and keep a consistent sequence so adjacent sections blend before they set.", reference: "Professional roller-application practice" },
  { id: 14, topic: "application", prompt: "A very rough masonry surface generally calls for which roller-cover choice?", choices: ["A longer nap that can reach the texture", "The shortest possible nap", "No cover at all", "A foam brush only"], answer: 0, explanation: "Rough surfaces usually require a longer nap, chosen within the coating manufacturer’s recommendations.", reference: "Professional roller-selection practice" },
  { id: 15, topic: "application", prompt: "Heavy sags appear immediately after spraying a vertical surface. The most likely cause is:", choices: ["Film applied too heavily", "Too little material", "A perfectly dry substrate", "Excessive masking"], answer: 0, explanation: "Runs and sags commonly result from excessive wet film, slow movement, incorrect setup, or excessive thinning.", reference: "Professional spray-application practice" },
  { id: 16, topic: "application", prompt: "Why are adjacent airless-spray passes commonly overlapped?", choices: ["To create even film coverage", "To double the pot life", "To eliminate masking", "To avoid inspecting the fan"], answer: 0, explanation: "Consistent overlap helps equalize film thickness and prevents light bands between passes.", reference: "Professional airless-spray practice" },
  { id: 17, topic: "application", prompt: "A spray fan shows heavy tails at both edges. What should the painter do first?", choices: ["Continue and hope it levels", "Stop and check pressure, tip condition, and material setup", "Move closer until the gun touches", "Remove the guard"], answer: 1, explanation: "Tails indicate poor atomization or a setup problem. Stop safely and diagnose the pressure, tip, filters, and coating requirements.", reference: "Airless-equipment operating guidance" },
  { id: 18, topic: "application", prompt: "When brush-cutting a wall next to trim before rolling, the painter should:", choices: ["Leave a dry gap", "Blend the rolled field into a still-workable cut line", "Use unstrained debris-filled paint", "Remove all masking while wet underfoot"], answer: 1, explanation: "Coordinating cut-in and rolling while edges remain workable reduces picture-framing and visible lap differences.", reference: "Professional brush-and-roll practice" },

  { id: 19, topic: "safety", prompt: "Where should a painter look for a product’s hazards, required PPE, first aid, and handling precautions?", choices: ["Only the color card", "The label and Safety Data Sheet", "The sales receipt", "A room finish schedule only"], answer: 1, explanation: "Hazard Communication requires accessible labels and safety data. Workers must be trained to use that information.", reference: "OSHA 29 CFR 1910.1200" },
  { id: 20, topic: "safety", prompt: "Before an employee is required to wear a tight-fitting respirator, which sequence is essential?", choices: ["Buy any mask and start work", "Medical evaluation, training, and fit testing under a respiratory program", "Grow facial hair at the seal", "Share a used cartridge"], answer: 1, explanation: "Required respirator use must be managed through a written program, including medical evaluation and fit testing.", reference: "OSHA 29 CFR 1910.134" },
  { id: 21, topic: "safety", prompt: "A high-pressure airless spray injection injury looks like a tiny puncture. What is the correct response?", choices: ["Finish the shift", "Treat it as an immediate medical emergency", "Cover it with paint", "Massage the area"], answer: 1, explanation: "Injected coating can cause severe internal injury even when the entry wound appears small. Stop work and obtain emergency medical care.", reference: "Airless-equipment safety guidance" },
  { id: 22, topic: "safety", prompt: "Under OSHA’s construction lead standard, the permissible exposure limit is:", choices: ["50 micrograms per cubic meter as an 8-hour TWA", "500 micrograms at any time", "5 milligrams per gallon", "No measurable amount in paint"], answer: 0, explanation: "The construction lead PEL is 50 µg/m³ averaged over an 8-hour workday; exposure assessment and controls may be required.", reference: "OSHA 29 CFR 1926.62(c)" },
  { id: 23, topic: "safety", prompt: "Solvent-wet rags should be handled according to the SDS and site procedure because they can:", choices: ["Improve ventilation", "Create fire and exposure hazards", "Replace drop cloths", "Make coatings waterborne"], answer: 1, explanation: "Contaminated rags can release vapors and, for some materials, contribute to spontaneous heating. Use approved covered containers and disposal procedures.", reference: "OSHA Hazard Communication / fire-safety practice" },
  { id: 24, topic: "safety", prompt: "Before spray painting in an enclosed area, the painter must verify controls for ventilation, ignition sources, and:", choices: ["Customer paint preference only", "Respiratory and exposure hazards", "The width of the sidewalk only", "Whether brushes are new"], answer: 1, explanation: "Spray work can create flammable atmospheres and airborne exposures. Follow the designated spray-area and respiratory controls.", reference: "OSHA 29 CFR 1910.107 and 1910.134" },

  { id: 25, topic: "access", prompt: "A non-self-supporting ladder used for access is generally set at what working angle?", choices: ["About 1 foot out for every 4 feet up", "1 foot out for every 1 foot up", "Completely horizontal", "Any angle that feels comfortable"], answer: 0, explanation: "OSHA describes the 4-to-1 setup for non-self-supporting ladders: horizontal distance about one-quarter of the working length.", reference: "OSHA 29 CFR 1926.1053(b)(5)(i)" },
  { id: 26, topic: "access", prompt: "When a portable ladder provides access to an upper landing, its side rails should normally extend at least:", choices: ["6 inches", "1 foot", "3 feet", "10 feet"], answer: 2, explanation: "Side rails must extend at least 3 feet above the landing, or the ladder must be secured with a grasping device provided.", reference: "OSHA 29 CFR 1926.1053(b)(1)" },
  { id: 27, topic: "access", prompt: "A scaffold and its components must support their own weight plus at least:", choices: ["The exact intended load", "Two times the load", "Four times the maximum intended load", "Ten pounds"], answer: 2, explanation: "Each scaffold and component must support its own weight and at least four times the maximum intended load, except as specifically provided.", reference: "OSHA 29 CFR 1926.451(a)(1)" },
  { id: 28, topic: "access", prompt: "Employees on a scaffold more than 10 feet above a lower level generally require:", choices: ["Fall protection", "Only a paint bucket", "A shorter roller pole", "No additional controls"], answer: 0, explanation: "OSHA’s scaffold rule generally requires protection from falling when workers are more than 10 feet above a lower level.", reference: "OSHA 29 CFR 1926.451(g)(1)" },
  { id: 29, topic: "access", prompt: "Who should inspect a scaffold before each work shift and after an event that could affect it?", choices: ["Any passerby", "A competent person", "The paint supplier", "Only the newest employee"], answer: 1, explanation: "A competent person must inspect the scaffold and components for visible defects before each shift and after affecting events.", reference: "OSHA 29 CFR 1926.451(f)(3)" },
  { id: 30, topic: "access", prompt: "A painter needs both hands for forceful overhead work from a stepladder. The safest planning choice is to:", choices: ["Stand on the top cap", "Choose a suitable platform or scaffold", "Lean the closed stepladder against a pipe", "Ask someone to shake the ladder"], answer: 1, explanation: "Choose access equipment that permits stable positioning and the required work. Do not use the top or top step of a stepladder as a step.", reference: "OSHA 29 CFR 1926.1053(b)(13)" },

  { id: 31, topic: "math", prompt: "A wall is 24 feet long and 10 feet high with no deductions. What is its area?", choices: ["34 sq ft", "120 sq ft", "240 sq ft", "480 sq ft"], answer: 2, explanation: "Area = length × height: 24 × 10 = 240 square feet.", reference: "Trade mathematics" },
  { id: 32, topic: "math", prompt: "A room has 1,200 paintable square feet and needs two coats. At 400 square feet per gallon, how many gallons are required before waste?", choices: ["3", "4", "6", "8"], answer: 2, explanation: "1,200 × 2 coats = 2,400 square feet of coverage. 2,400 ÷ 400 = 6 gallons.", reference: "Coverage calculation" },
  { id: 33, topic: "math", prompt: "A two-component coating uses a 4:1 ratio. For a 5-gallon mixed batch, how much activator is required?", choices: ["0.5 gallon", "1 gallon", "2 gallons", "4 gallons"], answer: 1, explanation: "There are 5 total parts. Each part is 1 gallon, so the activator is 1 gallon and the base is 4 gallons.", reference: "Ratio calculation" },
  { id: 34, topic: "math", prompt: "A calculated job needs 8 gallons. Adding a 10% waste allowance gives:", choices: ["8.1 gallons", "8.8 gallons", "9.8 gallons", "18 gallons"], answer: 1, explanation: "8 × 1.10 = 8.8 gallons. Purchase quantities should then be planned around available container sizes.", reference: "Estimating calculation" },
  { id: 35, topic: "math", prompt: "A drawing uses 1/4 inch = 1 foot. A wall measures 6 inches on the drawing. What is the actual length?", choices: ["6 feet", "12 feet", "18 feet", "24 feet"], answer: 3, explanation: "Each quarter inch represents 1 foot. Six inches contains 24 quarter-inch units, so the wall is 24 feet.", reference: "Blueprint scale calculation" },
  { id: 36, topic: "math", prompt: "A 12-by-9-foot wall contains a 3-by-7-foot door. What is the paintable wall area before coats?", choices: ["21 sq ft", "87 sq ft", "108 sq ft", "129 sq ft"], answer: 1, explanation: "Gross wall area is 108 square feet. Door area is 21 square feet. Net area is 87 square feet.", reference: "Area and deduction calculation" },

  { id: 37, topic: "drawings", prompt: "When a written dimension and a scaled measurement appear to disagree, the painter should:", choices: ["Ignore both", "Use the written dimension and request clarification if needed", "Always trust a phone photo", "Guess from memory"], answer: 1, explanation: "Written dimensions normally govern over scaling. Conflicts should be raised before material is ordered or work proceeds.", reference: "Blueprint-reading practice" },
  { id: 38, topic: "drawings", prompt: "What document commonly identifies room-by-room substrates, colors, and finish systems?", choices: ["Finish schedule", "Payroll register", "Vehicle title", "Weather map"], answer: 0, explanation: "A finish schedule organizes finish requirements and must be read with plans, notes, specifications, and revisions.", reference: "Construction-document practice" },
  { id: 39, topic: "drawings", prompt: "A needle scaler or needle gun is primarily useful to:", choices: ["Measure wall area", "Remove rust, scale, and loose coatings from irregular metal", "Cut glass circles", "Tint latex paint"], answer: 1, explanation: "Needle scalers use reciprocating needles to clean irregular steel surfaces. PPE and dust/exposure controls still apply.", reference: "Professional tool knowledge" },
  { id: 40, topic: "drawings", prompt: "Before replacing a cracked pane, the first planning step is to:", choices: ["Strike the glass with a hammer", "Secure the area and identify the glazing system and hazards", "Paint over the crack", "Heat unknown glazing compound"], answer: 1, explanation: "Control the work area, assess the frame and glazing method, and evaluate sharp-edge, lead, and other hazards before removal.", reference: "Professional glazing safety practice" },
  { id: 41, topic: "drawings", prompt: "Why should an airless spray tip be matched to the coating and required fan width?", choices: ["Tip choice controls delivery and spray pattern", "All tips produce the same film", "It changes the room dimensions", "It eliminates pressure hazards"], answer: 0, explanation: "Tip orifice and fan selection affect flow, atomization, pattern, and achievable film. Follow the coating and equipment guidance.", reference: "Airless-equipment operating guidance" },
  { id: 42, topic: "drawings", prompt: "A work order lacks the specified finish for one surface. The professional response is to:", choices: ["Use whatever is open", "Clarify the requirement before coating", "Skip preparation", "Copy a different building without approval"], answer: 1, explanation: "Resolve incomplete or conflicting instructions before work so the installed system matches the owner’s requirement.", reference: "Professional work-order practice" },

  { id: 43, topic: "transit", prompt: "Painting near an active passenger path requires the painter to prioritize:", choices: ["Fastest possible spraying", "Barricades, public protection, access, and approved work controls", "Leaving hoses across the walkway", "Open containers at platform edges"], answer: 1, explanation: "Transit work must protect riders and operations. Establish the authorized work zone and maintain safe movement and emergency access.", reference: "SEPTA job-safety expectations" },
  { id: 44, topic: "transit", prompt: "During preparation, the painter discovers an unknown old coating that may contain lead. What should happen?", choices: ["Dry-sand it immediately", "Stop disturbance and follow the hazard-assessment procedure", "Use compressed air to spread dust", "Ignore it outdoors"], answer: 1, explanation: "Unknown hazardous coatings require assessment and controls before disturbance. Do not create uncontrolled dust or debris.", reference: "OSHA 29 CFR 1926.62" },
  { id: 45, topic: "transit", prompt: "A station egress route passes through the planned work zone. The painter should:", choices: ["Block it without notice", "Coordinate the work so required egress remains protected", "Store ladders in the doorway", "Remove exit signs"], answer: 1, explanation: "Work planning must protect required exits and public movement. Changes require coordination with the responsible authority.", reference: "SEPTA safety and security expectations" },
  { id: 46, topic: "transit", prompt: "Before acetylene cutting during a painting assignment, what must be established?", choices: ["Only a color match", "Authorized hot-work controls, fire prevention, and trained operation", "An open solvent pail nearby", "A plastic drop cloth over sparks"], answer: 1, explanation: "Cutting is hot work. It requires authorization, area preparation, fire controls, suitable PPE, and trained personnel.", reference: "OSHA 29 CFR 1926 Subpart J / site hot-work procedure" },
  { id: 47, topic: "transit", prompt: "An airless hose is found with exposed reinforcement before work begins. The correct action is to:", choices: ["Wrap it with masking tape", "Remove it from service and replace it as required", "Increase pressure", "Hide the damaged section"], answer: 1, explanation: "High-pressure hose damage can lead to rupture or injection. Defective equipment must not be used.", reference: "Airless-equipment inspection guidance" },
  { id: 48, topic: "transit", prompt: "SEPTA’s Painter–First Class posting expects a painter to work from drawings and written instructions while also being able to:", choices: ["Ignore missing materials", "Problem-solve safely at the job site", "Alter transit service alone", "Bypass safety procedures"], answer: 1, explanation: "The role calls for independent problem-solving, clean work areas, and compliance with Authority safety and security procedures.", reference: "SEPTA Painter–First Class (1131) posting" },
];

export const practicalStations: PracticalStation[] = [
  { id: "drywall", number: "01", title: "Drywall repair & finish", time: "20 MIN", brief: "Repair a damaged gypsum-board area and leave it ready for primer.", checks: ["Protects the work area", "Removes loose material", "Applies compound in controlled coats", "Feathers and sands edges", "Removes dust and inspects with light"] },
  { id: "steel", number: "02", title: "Steel surface preparation", time: "20 MIN", brief: "Prepare a corroded steel sample for the assigned primer without damaging sound material.", checks: ["Selects correct tools and PPE", "Removes loose rust and coating", "Cleans corners and irregular areas", "Creates a uniform prepared surface", "Controls and collects debris"] },
  { id: "finish", number: "03", title: "Brush, cut & roll", time: "25 MIN", brief: "Produce a clean cut line and uniform wall finish with no holidays, runs, or heavy lap marks.", checks: ["Mixes and strains as directed", "Loads tools without excess", "Maintains a workable cut edge", "Keeps a wet edge", "Leaves uniform texture and clean boundaries"] },
  { id: "mix", number: "04", title: "Mixing & color control", time: "15 MIN", brief: "Calculate and prepare a small batch from a stated ratio while keeping the product traceable.", checks: ["Reads the full product instruction", "Calculates parts correctly", "Measures cleanly", "Records mix and start time", "Respects induction and pot life"] },
  { id: "airless", number: "05", title: "Airless setup & pattern", time: "20 MIN", brief: "Inspect an airless unit, select the assigned tip, and demonstrate a safe test pattern and shutdown.", checks: ["Finds hose, guard, and trigger hazards", "Confirms grounding and pressure controls", "Uses the specified tip and filters", "Tests at the lowest effective pressure", "Relieves pressure before service"] },
  { id: "access", number: "06", title: "Access-equipment decision", time: "15 MIN", brief: "Choose and inspect safe access for an elevated task requiring tools and two-handed work.", checks: ["Identifies height and task demands", "Rejects damaged equipment", "Sets stable footing and access", "Includes required fall protection", "Protects the area below"] },
  { id: "takeoff", number: "07", title: "Drawing & material takeoff", time: "20 MIN", brief: "Read a simple plan, calculate net area, coats, gallons, and a stated waste allowance.", checks: ["Reads scale and notes", "Uses written dimensions", "Deducts openings correctly", "Applies coats and coverage", "Shows units and rounds purchase quantities"] },
  { id: "hazard", number: "08", title: "Hazard-recognition walk", time: "15 MIN", brief: "Review a simulated transit work zone and explain the controls needed before work begins.", checks: ["Protects public movement and egress", "Finds lead and respiratory concerns", "Finds ignition and hot-work hazards", "Finds ladder, scaffold, and hose hazards", "Explains stop-work and reporting steps"] },
];

export const readinessItems = [
  "Document three years of relevant full-time painting experience",
  "Gather trade-school records if using the allowed one-year substitution",
  "Confirm a valid Pennsylvania driver’s license or equivalent",
  "Review brush, roller, epoxy, stain, oil-based, and waterborne systems",
  "Practice airless setup, maintenance, troubleshooting, and pressure relief",
  "Be ready to demonstrate safe ladder, plank, scaffold, and work-platform decisions",
  "Practice basic mathematics, plan reading, hand tools, and light carpentry",
  "Prepare for work at 32 feet or higher and SEPTA Q.P.E./flagging training",
  "Check the live SEPTA Careers page and follow only current hiring instructions",
];
